version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: lonca-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lonca_vendor_dashboard
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lonca-network

  redis:
    image: redis:7-alpine
    container_name: lonca-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - lonca-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lonca-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://mongodb:27017/lonca_vendor_dashboard
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    networks:
      - lonca-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lonca-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - lonca-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  lonca-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: